### ISSUE TITLE
transition from Karabiner to Karabiner Elements

### ISSUE THREAD

**Issue by januz** [rcmdnk/KE-complex_modifications#1] opened 2018-07-31 00:08 UTC
Hi @rcmdnk ,

I have been a long time user of your `vim_emu` for the original Karabiner. Indeed, I'm so reliant on it that it has been the main reason for me not to update to (High) Sierra. But as Apple officially de-continues El Capitan in September, I feel as though I have to make the jump soon. I found this repository in which you implement the `vim_emu` functions for Karabiner Elements. But I am wondering about what differences/shortcomings will result for me, especially

- can one also configure "kj" as switch? (I often hit them almost simultaneously)?
- can one configure different apps and key combinations (e.g., Ctrl-Space which activates Alfred for me) that reset the state to insert mode ([like my previous request](https://github.com/rcmdnk/vim_emu/issues/2))?
- can one use an indicator for when the state is not insert mode (in Karabiner, I have my menubar be colored red whenever `vim_emu` is activated?
- can a German keyboard be used?

Thank you so much for your help and all your work!

**Comment by rcmdnk** [comment] 2018-07-31 00:57
> can one also configure "kj" as switch? (I often hit them almost simultaneously)?

This is implemented. You can enable ESC/Ctrl-[ to enter Normal mode, or jk/sd to toggle Normal-Insert mode.

> can one configure different apps and key combinations (e.g., Ctrl-Space which activates Alfred for me) that reset the state to insert mode (like my previous request)?

I think this is possible though it is not so simple as Karabiner's setting...

> can one use an indicator for when the state is not insert mode (in Karabiner, I have my menubar be colored red whenever vim_emu is activated?

I don't know if current KE has such a function or not (I could not find by my quick search)

> can a German keyboard be used?

Yes, for KE. But I didn't care about German keyboard for vim_emu. It may work or may need to add some configurations.

**Comment by januz** [comment] 2018-07-31 05:34
>> can one also configure "kj" as switch? (I often hit them almost simultaneously)?

> This is implemented. You can enable ESC/Ctrl-[ to enter Normal mode, or jk/sd to toggle Normal-Insert mode.

Yes, I saw "jk", but I meant both "jk" and "kj", because I often just hit the keys and only "jk" would thus only activate in 50% of the cases. But I guess I'll be able to adjust/add this based on your setup.

>> can one configure different apps and key combinations (e.g., Ctrl-Space which activates Alfred for me) that reset the state to insert mode (like my previous request)?

> I think this is possible though it is not so simple as Karabiner's setting...

Do you have a pointer for me to look up how to implement it?

>> can one use an indicator for when the state is not insert mode (in Karabiner, I have my menubar be colored red whenever vim_emu is activated?

> I don't know if current KE has such a function or not (I could not find by my quick search)

I also didn't find it anything. I'll ask for this functionality in the main application.

>> can a German keyboard be used?

> Yes, for KE. But I didn't care about German keyboard for vim_emu. It may work or may need to add some configurations.

OK, I'll try it out over the next days and will try to make some adjustments if it doesn't work. I might bug you again to  ask for help :) Thank you!!

**Comment by rcmdnk** [comment] 2018-07-31 06:36
> Yes, I saw "jk", but I meant both "jk" and "kj", because I often just hit the keys and only "jk" would thus only activate in 50% of the cases. But I guess I'll be able to adjust/add this based on your setup.

I see. As you concerned, the current setting requires `j` first.
I think I can push `k` first case as well. (could make conflict, to be checked)

Around line 16 of  **src/json/vim_emu.json.erb**,
there is a setting of:

    {
      "description": "Vim emulation: Simultaneous jk to toggle normal-insert mode",
      "extra_description_level": 1,
      "manipulators": <%= vim_emu_simul("j", "k", hash_to([["down_arrow"]]), hash_to([["down_arrow", ["shift"]]]), true) %>
    },

If you put anotehr setting with `("k", "j", ...)` it will enable `k` first, maybe.

> Do you have a pointer for me to look up how to implement it?

You can refer around line 57 of **src/json/vim_emu.json.erb**,
how vim_emu changes mode from Normal to Insert.

There `vim_emu` function is used which is defined in  **scripts/erb2json.rb**.

Maybe you just need to add another `manipular` like 

        manipulators += vim_emu(
          source_keys_list: ["spacebar"],
          from_mandatory_modifiers=["control"]
          dest_keys_list: [
            [["spacebar", ["control"]]+vim_emu_mode(),
          ],
          mode: "normal",
        )

(not tested)

**Comment by januz** [comment] 2018-07-31 15:54
Thank you for your quick response! I'll try to figure it out over the next days.

**Comment by januz** [comment] 2018-08-06 06:03
Okay, I tried out your suggestions:

- adding an additional trigger "kj" to change to insert mode works!
- adding another manipulator to quit `vim_emu` on ctrl-space does not

I tried this code

```

        manipulators += vim_emu(
          source_keys_list: ["spacebar"],
          from_mandatory_modifiers: ["control"],
          dest_keys_list: [
             [["spacebar"], ["control"]] + vim_emu_mode(),
          ],
          mode: "normal",
        )
```

- this quits `vim_emu` (as it should)
- but then just types a space character (instead of executing ctrl-space to open Alfred)

Do you have any ideas what else I could try?

**Comment by rcmdnk** [comment] 2018-08-07 09:46
About the `spacebar`, it should be

```diff
-[["spacebar"], ["control"]] + vim_emu_mode(),
+[["spacebar", ["control"]]] + vim_emu_mode(),
```

but maybe it is just a typo here as it worked at least for quitting vim_emu.

Do set Ctrl-space in Alfred, or do you have another key set for Alfred in Karabiner?

If you set a shortcut to launch Alfred and you have a mapping of Ctrl-space to the shortcut,
then you need to write same destination keys instead of `[["spacebar", ["control"]]]`.

About jk simultaneous setting, I tried and found some wrong behaviors (may take time to understand...).

* jk and kj settngs make a conflict and only the first one works correctly.
* It works only for Insert to Normal, but doesn't work for Normal to Insert or Visual to Insert.
* Not a bug (known feature), but if you enable simultaneous key, it doesn't allow key repeat.

**Comment by januz** [comment] 2018-08-07 22:04
> but maybe it is just a typo here as it worked at least for quitting vim_emu

No, this was an actual coding error. Now it works! Thank you!! (I don't know why it worked partly before...)

> About jk simultaneous setting, I tried and found some wrong behaviors

That's sadly true as well. After I posted I ran into some problems and was trying to understand them better, before I post again. But you summed it up nicely already.

One further thing I realized regarding the mode switching: After every restart of Karabiner-Elements, I cannot use `simultaneous jk` immediately. Instead I first have to use `Esc` once. Afterwards I can use `simultaneous jk`. I don't know when this problem started appearing, but at least on my machine it's a reproducible error. The order of `Esc` and `simultaneous jk` in the rules list doesn't matter. Configuring only `simultaneous jk` without additional `Esc` (which would actually be my preferred configuration) doesn't work either.

*One last point:*

Because I really miss the possibility to display an indicator when `NORMAL` mode is on (like it was possible with Karabiner), I looked into possible mechanisms to replace it. One option I came up with would be to use an application called `BitBar` to display text/emoji/... in the menu bar once `NORMAL` mode gets activated and not when `INSERT` mode is activated.

For this to work I would need to execute a shell script whenever `NORMAL` mode is activated and another when `INSERT` mode is reactivated. I saw that it is generally possible to map shell scripts to keys in Karabiner-Elements (https://github.com/tekezo/Karabiner-Elements/issues/721#issuecomment-334499349). But could I include this in vim_emu, potentially by changing the `vim_emu_mode` function?

Thank you for your help!

**Comment by rcmdnk** [comment] 2018-08-08 05:13
>One further thing I realized regarding the mode switching: After every restart of Karabiner-Elements, I cannot use simultaneous jk immediately. Instead I first have to use Esc once.

This could be because vim_emu variables are not assigned at first.
For ESC, it doesn't have a condition for insert mode, but the simultaneous key setting has, because it is toggle and need another setting on Normal mode.
I think it can be avoided by reviewing the condition for jk.

> But could I include this in vim_emu, potentially by changing the vim_emu_mode function?

KE has `shell_command` event which can execute any shell command.
Maybe you can implement `shell_comamnd` in
`vim_emu_mode` of
https://github.com/rcmdnk/KE-complex_modifications/blob/master/scripts/erb2json.rb#L496.

Just before  `make_data(data, as_json)`, insert:

    if normal == 1
      data.push({"shell_command": "command to show normal"})
    elsif insert == 1
      data.push({"shell_command": "command to show insert"})
    end

and `make` with this script.
Just an idea and I may miss something, but I think you can go such a way.

**Comment by januz** [comment] 2018-08-08 16:02
> This could be because vim_emu variables are not assigned at first.

That make sense. Would it be possible to add another condition for the first `simultaneous jk`, i.e., if no vim_emu variables exist, set `NORMAL` mode?

> Maybe you can implement shell_comamnd in `vim_emu_mode`

That approach makes sense. I tried it out as you suggested, but it does not work. Weirdly, when I look at the generated json file (`docs/json/vim_emu.json`), it does not contain any `"shell_command"` lines, so the command doesn't seem to be written at all. I tested whether this was due to the if clause being wrongly specified, but even if I replace the if clause with a line `data.push({"shell_command": "osascript -e 'beep'"})`, it does not show up in the generated json file.

**EDIT**

I didn't realize that `update-json.sh` only updates the files if one of the `*erb` files has changed. As I was only changing the `erb2json.rb` script, the json files weren't updated. This works now. Thank you!

**Comment by rcmdnk** [comment] 2018-08-09 11:33
I found KE has now `simultaneous` for `from` condition:

[karabiner.json Reference Manual - Karabiner - Software for macOS](https://pqrs.org/osx/karabiner/json.html#simultaneous)

With this key, these simultaneous conditions are easily implemented and solved these problems.

You can try new vim_emu from: 
[Karabiner-Elements complex_modifications rules by rcmdnk](https://rcmdnk.com/KE-complex_modifications/)

(make sure to remove old settings before)

> jk and kj settings make a conflict and only the first one works correctly.

These conflicts could be solved even in the previous methods, but anyway, now both jk and kj are enabled.

With `simultaneous`, the timing becomes a bit severe (need to push within 50ms),
but you can change the timing in KE's preferences as following the above manual.

> It works only for Insert to Normal, but doesn't work for Normal to Insert or Visual to Insert.

This was because I didn't re-order rules.
JK toggle (or any mode change key settings) must be upper than the core part.
This is still necessary even with `simultaneous` input.

> Not a bug (known feature), but if you enable simultaneous key, it doesn't allow key repeat.

This is fixed by using `simultaneous` input.


>>This could be because vim_emu variables are not assigned at first.

>That make sense. Would it be possible to add another condition for the first simultaneous jk, i.e., if no vim_emu variables exist, set NORMAL mode?

Although I could not test because these variables are remained even I stop/start KE (by checking EventViewer),
I think new setting has no problem on this.



> I didn't realize that update-json.sh only updates the files if one of the *erb files has changed. As I was only changing the erb2json.rb script, the json files weren't updated. This works now. Thank you!

You can use `make rebuild` which force to update all json files even if erb files are not changed.

**Comment by januz** [comment] 2018-08-11 02:59
> You can try new vim_emu from

Thank you! This works wonderfully. The timing is also fine for me.

I only have one problem that I think might be related to the new simultaneous setting. I use an app called `SpaceLauncher` as my "HyperKey", mostly to launch programs. After using the new `vim_emu` settings, shortcuts involving j or k don't work reliably anymore (while those involving other keys do). Do you think this might be related to the simultaneous setting and do you think one could somehow circumvent it for cases in which the spacebar is being hold?

> Although I could not test because these variables are remained even I stop/start KE (by checking EventViewer),
I think new setting has no problem on this.

yes, it works!

> You can use make rebuild which force to update all json files even if erb files are not changed.

Thanks for the tip! I haven't used `make` much as you can see :)

**Comment by januz** [comment] 2018-08-11 03:20
one more thing...

I used to have double tap commands in Karabiner (e.g., double tap `command` to send selection to Alfred). I have [found](https://pqrs.org/osx/karabiner/json.html#typical-complex_modifications-examples-change-right-shift-x2-to-mission-control) how to specify them in Karabiner-Elements, but I don't know how incorporate this functionality into `vim_emu` (I would like to switch to `INSERT` mode when I execute the double tap...) as the `vim_emu()` function doesn't seem to have the required `to_delayed_action` variable.

Thank you for all your help!

**Comment by rcmdnk** [comment] 2018-08-15 01:50
> After using the new vim_emu settings, shortcuts involving j or k don't work reliably anymore (while those involving other keys do). Do you think this might be related to the simultaneous setting and do you think one could somehow circumvent it for cases in which the spacebar is being hold?

I tried Spacelauncher. For me, it didn't work well even when I switched off KE.
It is launched sometime, but not launched.
But maybe KE (or simultaneous setting only) related to your problem,
because I could not launch Spacelauncher on vim_emu enabled app at all.

Both of them hack key settings, there can be conflicts.

Maybe you can replace all Spacelauncher functions in KE,
which has shell command setting, so you can open app like:

     "to": [
            {
                "shell_command": "open -a '/Applications/Firefox.app'"
            }
        ]


> I used to have double tap commands in Karabiner 

I've added "Vim emulation: Right shift double tap to toggle normal-insert mode".

This function is made by [new function of vim_emu_double function in erb2json.rb](https://github.com/rcmdnk/KE-complex_modifications/blob/master/scripts/erb2json.rb#L571).

Right shift double tap example is here:
[KE-complex_modifications/vim_emu.json.erb at master · rcmdnk/KE-complex_modifications](https://github.com/rcmdnk/KE-complex_modifications/blob/master/src/json/vim_emu.json.erb#L26)

If you like to enable only Normal to Insert switch,
you may remove second and third "data" definitions in vim_emu_double,
or make another similar function.

If you want to enable another key, just add another definitions in erb like:

    {
      "description": "Vim emulation: left control double tap to toggle normal-insert mode",
      "extra_description_level": 1,
      "manipulators": <%= vim_emu_double("left_control", true) %>
    },

**Closed as completed** 2018-11-16 04:30 UTC
